SELECT * FROM T_PE_USUARIOS;
SELECT * FROM T_PE_ENDERECOS;
SELECT * FROM T_PE_RESIDENCIAS;
SELECT * FROM T_PE_COMODOS;
SELECT * FROM T_PE_ELETRODOMESTICOS;
SELECT * FROM T_PE_CONSUMO_MENSAL;
SELECT * FROM T_PE_PONTUACAO_USUARIO;