DROP TABLE T_PE_PONTUACAO_USUARIO CASCADE CONSTRAINTS;
DROP TABLE T_PE_CONSUMO_MENSAL CASCADE CONSTRAINTS;
DROP TABLE T_PE_ELETRODOMESTICOS CASCADE CONSTRAINTS;
DROP TABLE T_PE_COMODOS CASCADE CONSTRAINTS;
DROP TABLE T_PE_RESIDENCIAS CASCADE CONSTRAINTS;
DROP TABLE T_PE_ENDERECOS CASCADE CONSTRAINTS;
DROP TABLE T_PE_USUARIOS CASCADE CONSTRAINTS;
